version: "3.1"

services:
  db:
    image: mysql:8.0
    ports:
      - "3301:3301"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wp_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wp_network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.2.2-apache
    ports:
      - 5010:80
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
    volumes:
      - ./wp:/var/www/html
    networks:
      - wp_network

volumes:
  db-data:

networks:
  wp_network:
    driver: bridge
